# Generated by Django 4.1.5 on 2024-02-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='district',
            field=models.CharField(default='vzm', max_length=255),
            preserve_default=False,
        ),
    ]
