# Generated by Django 4.1.5 on 2024-01-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=255)),
                ('Murder', models.IntegerField()),
                ('Hurt', models.IntegerField()),
                ('AssaultonWomen', models.IntegerField()),
                ('KidnappingandAbduction', models.IntegerField()),
                ('Rape', models.IntegerField()),
                ('UnlawfulAssembly', models.IntegerField()),
                ('Theft', models.IntegerField()),
                ('Burglary', models.IntegerField()),
                ('ForgeryCheatingFraud', models.IntegerField()),
                ('OffencesRelatingtoDocumentsPropertyMarks', models.IntegerField()),
                ('RashDrivingonPublicway', models.IntegerField()),
                ('CriminalTrespass', models.IntegerField()),
            ],
        ),
    ]
