# Generated by Django 4.1.5 on 2024-02-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_district_scamreport_state_delete_yourdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamreport',
            name='image',
            field=models.ImageField(upload_to='static/scam_images/'),
        ),
    ]
